<?php
/**
 * SBC Theme - Dynamic CSS Fix
 */

// 1. Get WordPress Data safely
$title = get_the_title();
$acf_data = function_exists('get_fields') ? get_fields() : [];

// 2. Prepare the data object
$wp_data = [
    'title' => $title,
    'acf' => $acf_data
];

// 3. Load the index.html content
$html = file_get_contents( get_template_directory() . '/index.html' );

// 4. FIND THE CSS FILE DYNAMICALLY
// We look for the stylesheet generated by Next.js in the build
$css_dir = get_template_directory() . '/_next/static/chunks/';
$css_files = glob($css_dir . '*.css');
$css_link = '';

if (!empty($css_files)) {
    // Get the first CSS file found (usually there is only one main one)
    $css_filename = basename($css_files[0]);
    $css_url = get_template_directory_uri() . '/_next/static/chunks/' . $css_filename;
    $css_link = '<link rel="stylesheet" href="' . $css_url . '">';
}

// 5. Inject our data and CSS fix into the head
$script = '<script>window.SBC_WP_DATA = ' . json_encode($wp_data) . ';</script>';
$injections = $script . $css_link;

$html = str_replace('</head>', $injections . '</head>', $html);

// 6. Output final HTML
echo $html;
?>
